### ISSUE TITLE
Improvement request: unify encodings in liftric images

### ISSUE THREAD

**Issue by Khartris** [Liftric/compose-debian-jdk-yarn-angular#2]
The liftric/compose-debian-jdk-angular image and the [liftric/alpine-jdk-yarn-angular](https://github.com/Liftric/alpine-jdk-yarn-angular) image have different encodings set. The alpine-jdk image is based on the openjdk-alpine image which explicitly sets en.UTF-8 as the language/encoding ([see here](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/14/jdk/alpine/Dockerfile.hotspot.releases.full)). 
This causes encoding issues when using both images in one project. I propose to also set the encoding to en.UTF-8 in this image to prevent these types of issues. The following commands match the language settings to the openjdk-alpine image.
```
RUN apt -y install locales locales-all
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
```

**Comment by Ingwersaft** [comment]
Looking forward to your PR 😄
